generator:
  class: sfPropelGenerator
  param:
    model_class:           sfNestedComment
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_nested_comment
    with_propel_route:     1
    
    config:
      actions: ~
      fields:
        author_name:      { label: Author }
        content:          { label: Comment }
        commentableTitle: { label: In Response To }
        created_at:       { label: Submitted At }
        author_email:     { label: Email }
        author_url:       { label: Website }
      list:
        max_per_page: 5
        title:    Comments
        display:  [_author_name, _comment, commentableTitle]
        actions:  [ ]
        query_methods: [ recent ]
        object_actions:
          _edit: ~
          togglePublish: { name: publish/unpublish, action: togglePublish }
          reply:         { name: Reply, action: new }
          _delete: ~
      filter:
        class: sfNestedCommentFormFilter
        fields:
          content:
            widgetOptions: { with_empty: false }
      form:    ~
      edit:
        title: Edit Comment
        display: [author_name, author_email, author_url, content]
        fields:
          author_name:  { type: plain }
          author_email: { type: plain }
          author_url:   { type: plain }
          content:
            widgetAttributes: { rows: 20, cols: 100 }
      new:
        title: Reply
        display: [author_name, author_email, author_url, content, user_id]
        fields:
          content:
            widgetAttributes: { rows: 20, cols: 100 }
          author_name:
            widgetClass: sfWidgetFormInputHidden
          author_email:
            widgetClass: sfWidgetFormInputHidden
          author_url:
            widgetClass: sfWidgetFormInputHidden
          user_id:
            widgetClass: sfWidgetFormInputHidden
