#all:
#  sfNestedComment:
#    use_ajax:            true  # enable posting of comments in Ajax
#    max_recent:          5     # number of comments to display in the recent sidebar widget
#    enable:              true  # enable comments by default on new commentable object
#    use_gravatar:        true  # use gravatar
                         # set to 0 for unlimited comments
#    automoderation:      first_post  # triggers the automoderation of comments. Possible values are:
                         # true: comments are not published until a moderator accepts them
                         # first_post: the first comment of a user must be accepted, subsequent posts are accepted automatically
                         # false: comments are automatically accepted and published

#    nested:              true    # enable nested comments
#    nested_depth:        3       # max depth of comments
#    paging:              true    # enable comments paging
#    max_per_page:        5       # number of comments to display
#    sort_type:           desc    #
#    mail_alert:          true    # send an email to the blog owner when a comment is posted.
                                  # Possible values are:
                                  # true: send an email for every posted comment
                                  # moderated: send an email for every automoderated comment
#    from_email:          johndoe@xmail.com
#    allowed_tags:
#      a:              <a>
#      blockquote:     <blockquote>
#      code:           <code>
#      em:             <em>
#      i:              <i>
#      p:              <p>
#      strong:         <strong>